ExtDirectBundle_api:
    path:  /api.js
    defaults: { _controller: ExtDirectBundle:Direct:getApi }

ExtDirectBundle_route:
    path: /route
    defaults: { _controller: ExtDirectBundle:Direct:route }
